spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
      username: root
      password: root
      initial-size: 3 #初始化时建立物理连接的个数
      min-idle: 3 #最小连接池数量
      max-active: 10 #最大连接池数量
      max-wait: 60000 #获取连接时最大等待时间
      stat-view-servlet:
        login-username: admin #配置监控页面访问登录名称
        login-password: 123456 #配置监控页面访问密码
      filter:
        stat:
          log-slow-sql: true #是否开启慢sql查询监控
          slow-sql-millis: 1000 #慢SQL执行时间

#mybatis
mybatis:
  mapperLocations: classpath:mapper/**/*.xml
  typeAliasesPackage: cn.nianzx.**.domain
  #xml文件下划线自动转实体类驼峰
  configuration:
    map-underscore-to-camel-case: true